
// Generated by Cadence Genus(TM) Synthesis Solution 17.21-s010_1
// Generated on: Mar 27 2021 11:40:49 IST (Mar 27 2021 06:10:49 UTC)

// Verification Directory fv/core 

module core(clk, ext_reset);
  input clk, ext_reset;
  wire clk, ext_reset;
endmodule

