###############################################################
#  Generated by:      Cadence Innovus 17.13-s098_1
#  OS:                Linux x86_64(Host ID cad54)
#  Generated on:      Fri Apr  2 11:47:47 2021
#  Design:            core
#  Command:           saveFPlan core.fp
###############################################################

Version: 8

Head Box: 0.0000 0.0000 504.2400 497.8400
IO Box: 0.0000 0.0000 504.2400 497.8400
Core Box: 4.6200 4.4800 499.6200 493.3600
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: tsm3site 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 tsm3site 4.6200 4.4800 FS 750 1 0.6600 0.0000
DefRow: ROW_1 tsm3site 4.6200 9.5200 N 750 1 0.6600 0.0000
DefRow: ROW_2 tsm3site 4.6200 14.5600 FS 750 1 0.6600 0.0000
DefRow: ROW_3 tsm3site 4.6200 19.6000 N 750 1 0.6600 0.0000
DefRow: ROW_4 tsm3site 4.6200 24.6400 FS 750 1 0.6600 0.0000
DefRow: ROW_5 tsm3site 4.6200 29.6800 N 750 1 0.6600 0.0000
DefRow: ROW_6 tsm3site 4.6200 34.7200 FS 750 1 0.6600 0.0000
DefRow: ROW_7 tsm3site 4.6200 39.7600 N 750 1 0.6600 0.0000
DefRow: ROW_8 tsm3site 4.6200 44.8000 FS 750 1 0.6600 0.0000
DefRow: ROW_9 tsm3site 4.6200 49.8400 N 750 1 0.6600 0.0000
DefRow: ROW_10 tsm3site 4.6200 54.8800 FS 750 1 0.6600 0.0000
DefRow: ROW_11 tsm3site 4.6200 59.9200 N 750 1 0.6600 0.0000
DefRow: ROW_12 tsm3site 4.6200 64.9600 FS 750 1 0.6600 0.0000
DefRow: ROW_13 tsm3site 4.6200 70.0000 N 750 1 0.6600 0.0000
DefRow: ROW_14 tsm3site 4.6200 75.0400 FS 750 1 0.6600 0.0000
DefRow: ROW_15 tsm3site 4.6200 80.0800 N 750 1 0.6600 0.0000
DefRow: ROW_16 tsm3site 4.6200 85.1200 FS 750 1 0.6600 0.0000
DefRow: ROW_17 tsm3site 4.6200 90.1600 N 750 1 0.6600 0.0000
DefRow: ROW_18 tsm3site 4.6200 95.2000 FS 750 1 0.6600 0.0000
DefRow: ROW_19 tsm3site 4.6200 100.2400 N 750 1 0.6600 0.0000
DefRow: ROW_20 tsm3site 4.6200 105.2800 FS 750 1 0.6600 0.0000
DefRow: ROW_21 tsm3site 4.6200 110.3200 N 750 1 0.6600 0.0000
DefRow: ROW_22 tsm3site 4.6200 115.3600 FS 750 1 0.6600 0.0000
DefRow: ROW_23 tsm3site 4.6200 120.4000 N 750 1 0.6600 0.0000
DefRow: ROW_24 tsm3site 4.6200 125.4400 FS 750 1 0.6600 0.0000
DefRow: ROW_25 tsm3site 4.6200 130.4800 N 750 1 0.6600 0.0000
DefRow: ROW_26 tsm3site 4.6200 135.5200 FS 750 1 0.6600 0.0000
DefRow: ROW_27 tsm3site 4.6200 140.5600 N 750 1 0.6600 0.0000
DefRow: ROW_28 tsm3site 4.6200 145.6000 FS 750 1 0.6600 0.0000
DefRow: ROW_29 tsm3site 4.6200 150.6400 N 750 1 0.6600 0.0000
DefRow: ROW_30 tsm3site 4.6200 155.6800 FS 750 1 0.6600 0.0000
DefRow: ROW_31 tsm3site 4.6200 160.7200 N 750 1 0.6600 0.0000
DefRow: ROW_32 tsm3site 4.6200 165.7600 FS 750 1 0.6600 0.0000
DefRow: ROW_33 tsm3site 4.6200 170.8000 N 750 1 0.6600 0.0000
DefRow: ROW_34 tsm3site 4.6200 175.8400 FS 750 1 0.6600 0.0000
DefRow: ROW_35 tsm3site 4.6200 180.8800 N 750 1 0.6600 0.0000
DefRow: ROW_36 tsm3site 4.6200 185.9200 FS 750 1 0.6600 0.0000
DefRow: ROW_37 tsm3site 4.6200 190.9600 N 750 1 0.6600 0.0000
DefRow: ROW_38 tsm3site 4.6200 196.0000 FS 750 1 0.6600 0.0000
DefRow: ROW_39 tsm3site 4.6200 201.0400 N 750 1 0.6600 0.0000
DefRow: ROW_40 tsm3site 4.6200 206.0800 FS 750 1 0.6600 0.0000
DefRow: ROW_41 tsm3site 4.6200 211.1200 N 750 1 0.6600 0.0000
DefRow: ROW_42 tsm3site 4.6200 216.1600 FS 750 1 0.6600 0.0000
DefRow: ROW_43 tsm3site 4.6200 221.2000 N 750 1 0.6600 0.0000
DefRow: ROW_44 tsm3site 4.6200 226.2400 FS 750 1 0.6600 0.0000
DefRow: ROW_45 tsm3site 4.6200 231.2800 N 750 1 0.6600 0.0000
DefRow: ROW_46 tsm3site 4.6200 236.3200 FS 750 1 0.6600 0.0000
DefRow: ROW_47 tsm3site 4.6200 241.3600 N 750 1 0.6600 0.0000
DefRow: ROW_48 tsm3site 4.6200 246.4000 FS 750 1 0.6600 0.0000
DefRow: ROW_49 tsm3site 4.6200 251.4400 N 750 1 0.6600 0.0000
DefRow: ROW_50 tsm3site 4.6200 256.4800 FS 750 1 0.6600 0.0000
DefRow: ROW_51 tsm3site 4.6200 261.5200 N 750 1 0.6600 0.0000
DefRow: ROW_52 tsm3site 4.6200 266.5600 FS 750 1 0.6600 0.0000
DefRow: ROW_53 tsm3site 4.6200 271.6000 N 750 1 0.6600 0.0000
DefRow: ROW_54 tsm3site 4.6200 276.6400 FS 750 1 0.6600 0.0000
DefRow: ROW_55 tsm3site 4.6200 281.6800 N 750 1 0.6600 0.0000
DefRow: ROW_56 tsm3site 4.6200 286.7200 FS 750 1 0.6600 0.0000
DefRow: ROW_57 tsm3site 4.6200 291.7600 N 750 1 0.6600 0.0000
DefRow: ROW_58 tsm3site 4.6200 296.8000 FS 750 1 0.6600 0.0000
DefRow: ROW_59 tsm3site 4.6200 301.8400 N 750 1 0.6600 0.0000
DefRow: ROW_60 tsm3site 4.6200 306.8800 FS 750 1 0.6600 0.0000
DefRow: ROW_61 tsm3site 4.6200 311.9200 N 750 1 0.6600 0.0000
DefRow: ROW_62 tsm3site 4.6200 316.9600 FS 750 1 0.6600 0.0000
DefRow: ROW_63 tsm3site 4.6200 322.0000 N 750 1 0.6600 0.0000
DefRow: ROW_64 tsm3site 4.6200 327.0400 FS 750 1 0.6600 0.0000
DefRow: ROW_65 tsm3site 4.6200 332.0800 N 750 1 0.6600 0.0000
DefRow: ROW_66 tsm3site 4.6200 337.1200 FS 750 1 0.6600 0.0000
DefRow: ROW_67 tsm3site 4.6200 342.1600 N 750 1 0.6600 0.0000
DefRow: ROW_68 tsm3site 4.6200 347.2000 FS 750 1 0.6600 0.0000
DefRow: ROW_69 tsm3site 4.6200 352.2400 N 750 1 0.6600 0.0000
DefRow: ROW_70 tsm3site 4.6200 357.2800 FS 750 1 0.6600 0.0000
DefRow: ROW_71 tsm3site 4.6200 362.3200 N 750 1 0.6600 0.0000
DefRow: ROW_72 tsm3site 4.6200 367.3600 FS 750 1 0.6600 0.0000
DefRow: ROW_73 tsm3site 4.6200 372.4000 N 750 1 0.6600 0.0000
DefRow: ROW_74 tsm3site 4.6200 377.4400 FS 750 1 0.6600 0.0000
DefRow: ROW_75 tsm3site 4.6200 382.4800 N 750 1 0.6600 0.0000
DefRow: ROW_76 tsm3site 4.6200 387.5200 FS 750 1 0.6600 0.0000
DefRow: ROW_77 tsm3site 4.6200 392.5600 N 750 1 0.6600 0.0000
DefRow: ROW_78 tsm3site 4.6200 397.6000 FS 750 1 0.6600 0.0000
DefRow: ROW_79 tsm3site 4.6200 402.6400 N 750 1 0.6600 0.0000
DefRow: ROW_80 tsm3site 4.6200 407.6800 FS 750 1 0.6600 0.0000
DefRow: ROW_81 tsm3site 4.6200 412.7200 N 750 1 0.6600 0.0000
DefRow: ROW_82 tsm3site 4.6200 417.7600 FS 750 1 0.6600 0.0000
DefRow: ROW_83 tsm3site 4.6200 422.8000 N 750 1 0.6600 0.0000
DefRow: ROW_84 tsm3site 4.6200 427.8400 FS 750 1 0.6600 0.0000
DefRow: ROW_85 tsm3site 4.6200 432.8800 N 750 1 0.6600 0.0000
DefRow: ROW_86 tsm3site 4.6200 437.9200 FS 750 1 0.6600 0.0000
DefRow: ROW_87 tsm3site 4.6200 442.9600 N 750 1 0.6600 0.0000
DefRow: ROW_88 tsm3site 4.6200 448.0000 FS 750 1 0.6600 0.0000
DefRow: ROW_89 tsm3site 4.6200 453.0400 N 750 1 0.6600 0.0000
DefRow: ROW_90 tsm3site 4.6200 458.0800 FS 750 1 0.6600 0.0000
DefRow: ROW_91 tsm3site 4.6200 463.1200 N 750 1 0.6600 0.0000
DefRow: ROW_92 tsm3site 4.6200 468.1600 FS 750 1 0.6600 0.0000
DefRow: ROW_93 tsm3site 4.6200 473.2000 N 750 1 0.6600 0.0000
DefRow: ROW_94 tsm3site 4.6200 478.2400 FS 750 1 0.6600 0.0000
DefRow: ROW_95 tsm3site 4.6200 483.2800 N 750 1 0.6600 0.0000
DefRow: ROW_96 tsm3site 4.6200 488.3200 FS 750 1 0.6600 0.0000

############################################################################################
#  Track: dir start number space layer_num layer1 [firstColor] [isSameColor] [width] [rule]#
############################################################################################
Track: Y 0.2800 889 0.5600 1 6
Track: X 0.9900 509 0.9900 1 6
Track: X 0.3300 764 0.6600 1 5
Track: Y 0.2800 889 0.5600 1 5
Track: Y 0.2800 889 0.5600 1 4
Track: X 0.3300 764 0.6600 1 4
Track: X 0.3300 764 0.6600 1 3
Track: Y 0.2800 889 0.5600 1 3
Track: Y 0.2800 889 0.5600 1 2
Track: X 0.3300 764 0.6600 1 2
Track: X 0.3300 764 0.6600 1 1
Track: Y 0.2800 889 0.5600 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: X 501.9300 2 2.3100
GCellGrid: X 0.3300 77 6.6000
GCellGrid: X 0.0000 2 0.3300
GCellGrid: Y 493.0800 2 4.7600
GCellGrid: Y 0.2800 89 5.6000
GCellGrid: Y 0.0000 2 0.2800

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: VDD -pwr
PhysicalNet: VSS -gnd

#####################################################################################
# <PGNets>                                                                          #
#    <PGNet name="net_name">                                                        #
#       <HNet name="hnet_name">                                                     #
#          <Port hinst="hinst_name" name="port_name" direction="in|out|inout" />    #
#       </HNet>                                                                     #
#    </PGNet>                                                                       #
# </PGNets>                                                                         #
#####################################################################################

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################

###########################################################################
#  <MacroArrays>                                                          #
#      <MacroArray>                                                       #
#          ...                                                            #
#      </MacroArray>                                                      #
#      ...                                                                #
#  </MacroArrays>                                                         #
###########################################################################

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

###########################################################################
#  BlockRoutingHalo: <name> <space> <bottomLayer> <topLayer> <-lithoHalo> #
###########################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

###########################################################################
#  <HierarchicalPartitions>                                               #
#     <GlobalPinConstraints>                                              #
#         <PinSpacing spacing=val />                                      #
#         <PinWidth layer=layerId width=val />                            #
#         <PinDepth layer=layerId depth=val />                            #
#         <CornerToPinDistance distance=val />                            #
#     </GlobalPinConstraints>                                             #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val   #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val isMixedSignal=val >         #
#         <Net name="net_name" /> ...                                   #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <DefaultTechSite name="core" />                                   #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <PinToCornerDistance  totalCorners=nrCorners >                  #
#            <Corner number=<cornerNumber> distance=<distance> /> ...     #
#         </PinToCornerDistance >                                         #
#         <PinSpacingArea llx=val lly=val urx=val ury=val spacing=val />  #
#         <LayerWidthDepth layer=layerId width=w depth=d />               #
#         <PinConstraint>                                                 #
#            <Pin name="pinName" >                                      #
#               <edge2 edgeMap=val />                                    #
#               <spacing space=val />                                    #
#               <layer layerMap=xval />                                  #
#               <pinWidth width=val />                                   #
#               <pinDepth depth=val />                                   #
#               <location x=val y=val />                                 #
#            </Pin>                                                       #
#         </PinConstraint>                                                #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr        #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val >                           #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <GlobalPinConstraints>
        <PinSpacing spacing=2 />
        <CornerToPinDistance distance=5 />
    </GlobalPinConstraints>
    <Partition name="core" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=-1 pinSpacingWest=-1 pinSpacingSouth=-1 pinSpacingEast=-1 blockedLayers=0x3f orient=R0>
	<PinLayer side="N" Metal2=yes Metal4=yes Metal6=yes />
	<PinLayer side="W" Metal3=yes Metal5=yes />
	<PinLayer side="S" Metal2=yes Metal4=yes Metal6=yes />
	<PinLayer side="E" Metal3=yes Metal5=yes />
    <PinToCornerDistance totalCorners=4 >
      <Corner number=0 distance=-1 />
      <Corner number=1 distance=-1 />
      <Corner number=2 distance=-1 />
      <Corner number=3 distance=-1 />
    </PinToCornerDistance>
    </Partition>
</HierarchicalPartitions>

####################################################################################
#  <PlacementBlockages>                                                            #
#     <Blockage name="blk_name" type="hard|soft|partial">                      #
#       <Attr density=1.2 excludeFlops=yes inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                        #
#     </Blockage>                                                                  #
#  </PlacementBlockages>                                                           #
####################################################################################

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

##########################################################################################################
#  <RouteBlockages>                                                                                      #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">                              #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes exceptpgnet=yes pgnetonly=yes />  #
#       <Layer type="route|cut|masterslice" id=layerNo />                                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                                              #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                                                      #
#     </Blockage>                                                                                        #
#  </RouteBlockages>                                                                                     #
##########################################################################################################

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

###########################################################################################
# NetbottomPreferredRoutingLayer:  <net_name> <bottomPreferredRoutingLayer (in integer)>  #
###########################################################################################

################################################################
# NetAvoidDetour:  <net_name>  < avoidDetour  { 1| 0}>   #
################################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: core.fp.spr

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 BotMask=2 CutMask=1 TopMask=2 />...  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <NETEXPR>                                                             #
#        ground VSS                                                          #
#      </NETEXPR> ...                                                        #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################

<IOPins>
  <Pin name="rs2_val_sx[31]" >
  </Pin>
  <Pin name="rs2_val_sx[30]" >
  </Pin>
  <Pin name="rs2_val_sx[29]" >
  </Pin>
  <Pin name="rs2_val_sx[28]" >
  </Pin>
  <Pin name="rs2_val_sx[27]" >
  </Pin>
  <Pin name="rs2_val_sx[26]" >
  </Pin>
  <Pin name="rs2_val_sx[25]" >
  </Pin>
  <Pin name="rs2_val_sx[24]" >
  </Pin>
  <Pin name="rs2_val_sx[23]" >
  </Pin>
  <Pin name="rs2_val_sx[22]" >
  </Pin>
  <Pin name="rs2_val_sx[21]" >
  </Pin>
  <Pin name="rs2_val_sx[20]" >
  </Pin>
  <Pin name="rs2_val_sx[19]" >
  </Pin>
  <Pin name="rs2_val_sx[18]" >
  </Pin>
  <Pin name="rs2_val_sx[17]" >
  </Pin>
  <Pin name="rs2_val_sx[16]" >
  </Pin>
  <Pin name="rs2_val_sx[15]" >
  </Pin>
  <Pin name="rs2_val_sx[14]" >
  </Pin>
  <Pin name="rs2_val_sx[13]" >
  </Pin>
  <Pin name="rs2_val_sx[12]" >
  </Pin>
  <Pin name="rs2_val_sx[11]" >
  </Pin>
  <Pin name="rs2_val_sx[10]" >
  </Pin>
  <Pin name="rs2_val_sx[9]" >
  </Pin>
  <Pin name="rs2_val_sx[8]" >
  </Pin>
  <Pin name="rs2_val_sx[7]" >
  </Pin>
  <Pin name="rs2_val_sx[6]" >
  </Pin>
  <Pin name="rs2_val_sx[5]" >
  </Pin>
  <Pin name="rs2_val_sx[4]" >
  </Pin>
  <Pin name="rs2_val_sx[3]" >
  </Pin>
  <Pin name="rs2_val_sx[2]" >
  </Pin>
  <Pin name="rs2_val_sx[1]" >
  </Pin>
  <Pin name="rs2_val_sx[0]" >
  </Pin>
  <Pin name="alu_addr[31]" >
  </Pin>
  <Pin name="alu_addr[30]" >
  </Pin>
  <Pin name="alu_addr[29]" >
  </Pin>
  <Pin name="alu_addr[28]" >
  </Pin>
  <Pin name="alu_addr[27]" >
  </Pin>
  <Pin name="alu_addr[26]" >
  </Pin>
  <Pin name="alu_addr[25]" >
  </Pin>
  <Pin name="alu_addr[24]" >
  </Pin>
  <Pin name="alu_addr[23]" >
  </Pin>
  <Pin name="alu_addr[22]" >
  </Pin>
  <Pin name="alu_addr[21]" >
  </Pin>
  <Pin name="alu_addr[20]" >
  </Pin>
  <Pin name="alu_addr[19]" >
  </Pin>
  <Pin name="alu_addr[18]" >
  </Pin>
  <Pin name="alu_addr[17]" >
  </Pin>
  <Pin name="alu_addr[16]" >
  </Pin>
  <Pin name="alu_addr[15]" >
  </Pin>
  <Pin name="alu_addr[14]" >
  </Pin>
  <Pin name="alu_addr[13]" >
  </Pin>
  <Pin name="alu_addr[12]" >
  </Pin>
  <Pin name="alu_addr[11]" >
  </Pin>
  <Pin name="alu_addr[10]" >
  </Pin>
  <Pin name="alu_addr[9]" >
  </Pin>
  <Pin name="alu_addr[8]" >
  </Pin>
  <Pin name="alu_addr[7]" >
  </Pin>
  <Pin name="alu_addr[6]" >
  </Pin>
  <Pin name="alu_addr[5]" >
  </Pin>
  <Pin name="alu_addr[4]" >
  </Pin>
  <Pin name="alu_addr[3]" >
  </Pin>
  <Pin name="alu_addr[2]" >
  </Pin>
  <Pin name="alu_addr[1]" >
  </Pin>
  <Pin name="alu_addr[0]" >
  </Pin>
  <Pin name="mem_we_in[3]" >
  </Pin>
  <Pin name="mem_we_in[2]" >
  </Pin>
  <Pin name="mem_we_in[1]" >
  </Pin>
  <Pin name="mem_we_in[0]" >
  </Pin>
  <Pin name="pc_out[31]" >
  </Pin>
  <Pin name="pc_out[30]" >
  </Pin>
  <Pin name="pc_out[29]" >
  </Pin>
  <Pin name="pc_out[28]" >
  </Pin>
  <Pin name="pc_out[27]" >
  </Pin>
  <Pin name="pc_out[26]" >
  </Pin>
  <Pin name="pc_out[25]" >
  </Pin>
  <Pin name="pc_out[24]" >
  </Pin>
  <Pin name="pc_out[23]" >
  </Pin>
  <Pin name="pc_out[22]" >
  </Pin>
  <Pin name="pc_out[21]" >
  </Pin>
  <Pin name="pc_out[20]" >
  </Pin>
  <Pin name="pc_out[19]" >
  </Pin>
  <Pin name="pc_out[18]" >
  </Pin>
  <Pin name="pc_out[17]" >
  </Pin>
  <Pin name="pc_out[16]" >
  </Pin>
  <Pin name="pc_out[15]" >
  </Pin>
  <Pin name="pc_out[14]" >
  </Pin>
  <Pin name="pc_out[13]" >
  </Pin>
  <Pin name="pc_out[12]" >
  </Pin>
  <Pin name="pc_out[11]" >
  </Pin>
  <Pin name="pc_out[10]" >
  </Pin>
  <Pin name="pc_out[9]" >
  </Pin>
  <Pin name="pc_out[8]" >
  </Pin>
  <Pin name="pc_out[7]" >
  </Pin>
  <Pin name="pc_out[6]" >
  </Pin>
  <Pin name="pc_out[5]" >
  </Pin>
  <Pin name="pc_out[4]" >
  </Pin>
  <Pin name="pc_out[3]" >
  </Pin>
  <Pin name="pc_out[2]" >
  </Pin>
  <Pin name="pc_out[1]" >
  </Pin>
  <Pin name="pc_out[0]" >
  </Pin>
  <Pin name="clk" >
  </Pin>
  <Pin name="ext_reset" >
  </Pin>
  <Pin name="mem_out[31]" >
  </Pin>
  <Pin name="mem_out[30]" >
  </Pin>
  <Pin name="mem_out[29]" >
  </Pin>
  <Pin name="mem_out[28]" >
  </Pin>
  <Pin name="mem_out[27]" >
  </Pin>
  <Pin name="mem_out[26]" >
  </Pin>
  <Pin name="mem_out[25]" >
  </Pin>
  <Pin name="mem_out[24]" >
  </Pin>
  <Pin name="mem_out[23]" >
  </Pin>
  <Pin name="mem_out[22]" >
  </Pin>
  <Pin name="mem_out[21]" >
  </Pin>
  <Pin name="mem_out[20]" >
  </Pin>
  <Pin name="mem_out[19]" >
  </Pin>
  <Pin name="mem_out[18]" >
  </Pin>
  <Pin name="mem_out[17]" >
  </Pin>
  <Pin name="mem_out[16]" >
  </Pin>
  <Pin name="mem_out[15]" >
  </Pin>
  <Pin name="mem_out[14]" >
  </Pin>
  <Pin name="mem_out[13]" >
  </Pin>
  <Pin name="mem_out[12]" >
  </Pin>
  <Pin name="mem_out[11]" >
  </Pin>
  <Pin name="mem_out[10]" >
  </Pin>
  <Pin name="mem_out[9]" >
  </Pin>
  <Pin name="mem_out[8]" >
  </Pin>
  <Pin name="mem_out[7]" >
  </Pin>
  <Pin name="mem_out[6]" >
  </Pin>
  <Pin name="mem_out[5]" >
  </Pin>
  <Pin name="mem_out[4]" >
  </Pin>
  <Pin name="mem_out[3]" >
  </Pin>
  <Pin name="mem_out[2]" >
  </Pin>
  <Pin name="mem_out[1]" >
  </Pin>
  <Pin name="mem_out[0]" >
  </Pin>
  <Pin name="instruction[31]" >
  </Pin>
  <Pin name="instruction[30]" >
  </Pin>
  <Pin name="instruction[29]" >
  </Pin>
  <Pin name="instruction[28]" >
  </Pin>
  <Pin name="instruction[27]" >
  </Pin>
  <Pin name="instruction[26]" >
  </Pin>
  <Pin name="instruction[25]" >
  </Pin>
  <Pin name="instruction[24]" >
  </Pin>
  <Pin name="instruction[23]" >
  </Pin>
  <Pin name="instruction[22]" >
  </Pin>
  <Pin name="instruction[21]" >
  </Pin>
  <Pin name="instruction[20]" >
  </Pin>
  <Pin name="instruction[19]" >
  </Pin>
  <Pin name="instruction[18]" >
  </Pin>
  <Pin name="instruction[17]" >
  </Pin>
  <Pin name="instruction[16]" >
  </Pin>
  <Pin name="instruction[15]" >
  </Pin>
  <Pin name="instruction[14]" >
  </Pin>
  <Pin name="instruction[13]" >
  </Pin>
  <Pin name="instruction[12]" >
  </Pin>
  <Pin name="instruction[11]" >
  </Pin>
  <Pin name="instruction[10]" >
  </Pin>
  <Pin name="instruction[9]" >
  </Pin>
  <Pin name="instruction[8]" >
  </Pin>
  <Pin name="instruction[7]" >
  </Pin>
  <Pin name="instruction[6]" >
  </Pin>
  <Pin name="instruction[5]" >
  </Pin>
  <Pin name="instruction[4]" >
  </Pin>
  <Pin name="instruction[3]" >
  </Pin>
  <Pin name="instruction[2]" >
  </Pin>
  <Pin name="instruction[1]" >
  </Pin>
  <Pin name="instruction[0]" >
  </Pin>
</IOPins>

#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="core">
  </Design>
</Properties>

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
